// File generated by project setup; align with Firebase Console / flutterfire configure.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Android values match `android/app/google-services.json`.
/// Windows uses the same Firebase project as web (add a dedicated Windows app in
/// the Firebase Console and run `flutterfire configure` if you need a separate client ID).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk5W6uTGYRP5xZxy4KDk1exSboQLpLN4E',
    appId: '1:727417603023:web:e5bfd8e01ea6a9706508ba',
    messagingSenderId: '727417603023',
    projectId: 'rescue-app-c79cf',
    authDomain: 'rescue-app-c79cf.firebaseapp.com',
    databaseURL:
        'https://rescue-app-c79cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-app-c79cf.firebasestorage.app',
    measurementId: 'G-YKNNEVKM86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCkpb0dANXiQA8Fl84DKzcJLfLvjuJoKE',
    appId: '1:727417603023:android:bf884e4293525acc6508ba',
    messagingSenderId: '727417603023',
    projectId: 'rescue-app-c79cf',
    databaseURL:
        'https://rescue-app-c79cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-app-c79cf.firebasestorage.app',
  );

  /// Same project as [web]; iOS/macOS targets can be replaced after adding apps in Console.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk5W6uTGYRP5xZxy4KDk1exSboQLpLN4E',
    appId: '1:727417603023:web:e5bfd8e01ea6a9706508ba',
    messagingSenderId: '727417603023',
    projectId: 'rescue-app-c79cf',
    authDomain: 'rescue-app-c79cf.firebaseapp.com',
    databaseURL:
        'https://rescue-app-c79cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-app-c79cf.firebasestorage.app',
    measurementId: 'G-YKNNEVKM86',
  );

  static const FirebaseOptions macos = ios;

  /// Explicit options so [Firebase.initializeApp] does not rely on native files (required for Windows).
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk5W6uTGYRP5xZxy4KDk1exSboQLpLN4E',
    appId: '1:727417603023:web:e5bfd8e01ea6a9706508ba',
    messagingSenderId: '727417603023',
    projectId: 'rescue-app-c79cf',
    authDomain: 'rescue-app-c79cf.firebaseapp.com',
    databaseURL:
        'https://rescue-app-c79cf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rescue-app-c79cf.firebasestorage.app',
    measurementId: 'G-YKNNEVKM86',
  );

  static const FirebaseOptions linux = windows;
}
